#!/bin/bash
clear

# Detectar distro
DISTRO="Desconhecido"
. /etc/os-release
echo " "
echo "Distribuição linux detectada:"
DISTRO=$ID
echo "$DISTRO"
echo " "

# Detectar o gerenciador de pacotes da distro
INSTALAR="echo"
if [ $DISTRO == "debian" ]; then
  echo 'O gerenciador de pacotes apt está instalado' >&2
  apt install -y sudo
  INSTALAR="sudo apt install -y"
fi

DISTRO="Desconhecido"
if ! [ -x "$(command -v apt-get)" ]; then
  :
else
  INSTALAR="sudo apt-get install -y"
  :
fi
if ! [ -x "$(command -v apt)" ]; then
  :
else
  INSTALAR="sudo apt install -y"
  :
fi
if ! [ -x "$(command -v nala)" ]; then
  :
else
  INSTALAR="sudo nala install --assume-yes"
  echo 'O gerenciador de pacotes nala está instalado' >&2
fi
if ! [ -x "$(command -v pacman)" ]; then
  :
else
  echo 'O gerenciador de pacotes pacman está instalado' >&2
  INSTALAR="sudo pacman -S --no-confirm"
fi
if ! [ -x "$(command -v pamac)" ]; then
  :
else
  echo 'O gerenciador de pacotes pamac está instalado' >&2
  INSTALAR="sudo pamac install --no-confirm"
fi
if ! [ -x "$(command -v dnf)" ]; then
  :
else
  echo 'O gerenciador de pacotes dnf está instalado' >&2
  INSTALAR="sudo dnf install -y"
fi
if ! [ -x "$(command -v yum)" ]; then
  :
else
  echo 'O gerenciador de pacotes yum está instalado' >&2
  INSTALAR="sudo yum install"
fi
if ! [ -x "$(command -v zypper)" ]; then
  :
else
  echo 'O gerenciador de pacotes zypper está instalado' >&2
  INSTALAR="sudo zypper install"
fi
if ! [ -x "$(command -v eopkg)" ]; then
  :
else
  echo 'O gerenciador de pacotes eopkg está instalado' >&2
  INSTALAR="sudo eopkg install"
fi
if ! [ -x "$(command -v apk)" ]; then
  :
else
  echo 'O gerenciador de pacotes apk está instalado' >&2
  INSTALAR="sudo apk add"
fi
if ! [ -x "$(command -v urpmi)" ]; then
  :
else
  echo 'O gerenciador de pacotes urpmi está instalado' >&2
  INSTALAR="urpmi"
fi
if ! [ -x "$(command -v xbps-install)" ]; then
  :
else
  echo 'O gerenciador de pacotes xbps-install está instalado' >&2
  INSTALAR="sudo xbps-install -S"
fi
if ! [ -x "$(command -v neko)" ]; then
  :
else
  echo 'O gerenciador de pacotes neko está instalado' >&2
  INSTALAR="sudo neko em"
fi
if ! [ -x "$(command -v pisi)" ]; then
  :
else
  echo 'O gerenciador de pacotes pisi está instalado' >&2
  INSTALAR="sudo pisi it"
fi
if ! [ -x "$(command -v guix)" ]; then
  :
else
  echo 'O gerenciador de pacotes guix está instalado' >&2
  INSTALAR="guix install"
fi

# Instalar apps essenciais para o terminal
if ! [ -x "$(command -v git)" ]; then
  $INSTALAR git
else
  echo 'git já estava instalado.' >&2
fi
if ! [ -x "$(command -v gh)" ]; then
  $INSTALAR gh
  $INSTALAR github-cli
else
  echo 'github-cli já estava instalado.' >&2
fi
if ! [ -x "$(command -v curl)" ]; then
  $INSTALAR curl
else
  echo 'curl já estava instalado.' >&2
fi
if ! [ -x "$(command -v wget)" ]; then
  $INSTALAR wget
else
  echo 'wget já estava instalado.' >&2
fi
if ! [ -x "$(command -v flatpak)" ]; then
  echo 'flatpak não instalado.' >&2
  $INSTALAR flatpak
else
  echo 'flatpak já estava instalado.' >&2
fi

# Drivers adicionais HP
$INSTALAR hplip

echo "Copiando scripts"
echo "Scripts atualizados em:" > $HOME/0_data_atualizado.txt
cd $HOME
rm -rf LinuxScripts
git clone https://github.com/riqueenz/LinuxScripts.git
cd LinuxScripts
chmod +x *
sudo \cp * /usr/bin
if [ $DISTRO == "manjaro" ] || [ $DISTRO == "arch" ]; then
  sudo \cp $HOME/LinuxScripts/config/etc/security/faillock.conf /etc/security/faillock.conf
fi
rm -rf ../LinuxScripts
cd $HOME

flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub --system --assumeyes com.google.Chrome
flatpak install flathub --system --assumeyes eu.scarpetta.PDFMixTool
flatpak install flathub --system --assumeyes io.github.shiftey.Desktop # GitHub Desktop
flatpak install flathub --system --assumeyes org.freecad.FreeCAD
if ! [ -x "$(command -v openshot)" ]; then
  flatpak install flathub --system --assumeyes org.openshot.OpenShot
else
  echo 'openshot já estava instalado.' >&2
fi
if ! [ -x "$(command -v vlc)" ]; then
  flatpak install flathub --system --assumeyes org.videolan.VLC
else
  echo 'vlc já estava instalado.' >&2
fi
if ! [ -x "$(command -v remmina)" ]; then
  flatpak install flathub --system --assumeyes org.remmina.Remmina
else
  echo 'remmina já estava instalado.' >&2
fi
if ! [ -x "$(command -v libreoffice)" ]; then
  flatpak install flathub --system --assumeyes org.libreoffice.LibreOffice
else
  echo 'libreoffice já estava instalado.' >&2
fi
if ! [ -x "$(command -v gimp)" ]; then
  flatpak install flathub --system --assumeyes org.gimp.GIMP
else
  echo 'gimp já estava instalado.' >&2
fi
if ! [ -x "$(command -v desktopeditors)" ]; then
  flatpak install flathub --system --assumeyes org.onlyoffice.desktopeditors
else
  echo 'onlyoffice já estava instalado.' >&2
fi
if ! [ -x "$(command -v openscad)" ]; then
  flatpak install flathub --system --assumeyes org.openscad.OpenSCAD
else
  echo 'openscad já estava instalado.' >&2
fi
if ! [ -x "$(command -v virtualbox)" ]; then
  instalar_virtualbox
else
  echo 'virtualbox já estava instalado.' >&2
fi
if ! [ -x "$(command -v distrobox)" ]; then
  instalar_distrobox
else
  echo 'distrobox já estava instalado.' >&2
fi

#Pasta de backup do sistema
mkdir $HOME/Documentos/Zistema
echo " "
echo "Fim do script!"
