#!/bin/bash 
. detectar_distro
echo " " >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações do kernel Manjaro:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

if [ $KERNEL != "6.12" ]; then
  echo "Instalando kernel 6.12"
  yes s | mhwd-kernel -i linux612
fi

if [ $KERNEL != "6.18" ]; then
  echo "Instalando kernel 6.18"
  yes s | mhwd-kernel -i linux618
fi

if [ $KERNEL == "6.18" ]; then
  echo "Kernel 6.18 está instalado!"
  echo "Removendo kernel antigo se houver..."
  yes s | mhwd-kernel -r linux515
  yes s | mhwd-kernel -r linux61
fi

echo "Final do script do kernel Manjaro:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
mhwd-kernel -li
