#!/bin/bash 
. detectar_distro
if [ $DISTRO == "ubuntu" ]; then
  atualizar
  sudo apt install ubuntu-release-upgrader-core -y
  do-release-upgrade
  atualizar
  cat /etc/os-release
fi
if [ $DISTRO == "debian" ]; then
  atualizar
  #atualizar /etc/apt/sources.list
  sudo apt dist-upgrade
  atualizar
  cat /etc/os-release
fi
