#!/bin/bash 
echo "snap refresh"
snap refresh
systemctl enable --now snapd.apparmor
echo " " >> $HOME/0_data_atualizado.txt
echo "Snap atualizado em:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
