#!/bin/bash
mv $HOME/Documentos/GitHub/Notas $HOME/Documentos/GitHub/Notas-backup
cd $HOME/Documentos/GitHub
git clone https://github.com/riqueenz/Notas.git
cd $HOME/Documentos/GitHub/Notas/
git add *
git commit * -m "Atualizar tarefas"
git push -u origin main
if [ -d "$HOME/Documentos/GitHub/Notas/" ]; then
  rm -rf $HOME/Documentos/GitHub/Notas-backup
fi

