#!/bin/bash 
apt update
echo "apt update"
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = apt" >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

apt upgrade -y
echo "apt upgrade -y"
echo " " >> $HOME/0_data_atualizado.txt
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

apt clean
echo "apt clean"
apt autoremove
echo "apt autoremove"
apt autoclean
echo "apt autoclean"
apt autoremove --purge
echo "apt autoremove --purge"
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
echo "Obs: AUR desativado" >> $HOME/0_data_atualizado.txt
