#!/bin/bash 
apk update
echo "apk update"
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = apk" >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

apk upgrade
echo "apk upgrade"
echo " " >> $HOME/0_data_atualizado.txt
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

apk cache clean
echo "apk cache clean"
apk autoremove
echo "apk autoremove"
apk fix
echo "apk fix"
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
