#!/bin/bash 
. detectar_distro

echo "Atualizando scripts"
echo "Scripts atualizados em:" >> $HOME/0_data_atualizado.txt
cd $HOME
rm -rf LinuxScripts
git clone https://github.com/riqueenz/LinuxScripts.git
cd LinuxScripts
chmod +x *
\cp * /usr/bin
if [ $DISTRO == "manjaro" ] || [ $DISTRO == "arch" ]; then
  echo "Atualizando configuração do faillock"
  echo "Configuração do faillock atualizado em:" >> $HOME/0_data_atualizado.txt
  \cp $HOME/LinuxScripts/config/etc/security/faillock.conf /etc/security/faillock.conf
fi
rm -rf ../LinuxScripts
cd $HOME
echo $(date) >> $HOME/0_data_atualizado.txt

echo "Atualizando configuração do Crontab"
echo "Configuração do crontab atualizado em:" >> $HOME/0_data_atualizado.txt
crontab_configurar
echo $(date) >> $HOME/0_data_atualizado.txt
