#!/bin/bash 
echo "pamac checkupdate --no-confirm"
pamac checkupdates --no-confirm
#pamac checkupdate --aur --no-confirm
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = pamac" >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

echo "pamac upgrade --force-refresh --no-confirm"
pamac upgrade --force-refresh --no-confirm
#pamac upgrade --aur --force-refresh --no-confirm
echo " " >> $HOME/0_data_atualizado.txt
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

echo "pamac clean --no-confirm"
pamac clean --no-confirm
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
echo "Obs: AUR desativado" >> $HOME/0_data_atualizado.txt
