#!/bin/bash 
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = pacman" >> $HOME/0_data_atualizado.txt
echo "pacman -Syu --noconfirm"
pacman -Syu --noconfirm
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

echo "rm -rf /var/cache/pacman/pkg/*"
rm -rf /var/cache/pacman/pkg/*
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
echo "Obs: AUR desativado" >> $HOME/0_data_atualizado.txt

# Procedimentos temporários
if pacman -Q btrfsmaintenance &> /dev/null; then
    echo "O pacote btrfsmaintenance está instalado. Iniciando a atualização..."
    echo "Consertar Aviso: btrfsmaintenance: local (1:0.5.2-1) é mais novo que extra (0.5.2-3) manjaro (02/10/2026)"
    echo "pacman -Syuu --noconfirm btrfsmaintenance"
    sudo pacman -Syuu --noconfirm btrfsmaintenance
else
    echo "O pacote btrfsmaintenance não está instalado no sistema."
fi

VERSAO_LIBCUPSFILTERS=$(pacman -Q libcupsfilters)
if [[ "$VERSAO_LIBCUPSFILTERS" == "libcupsfilters 2.1.1-4" ]]; then
    echo "A versão correta do libcupsfilters está instalada"
    pacman -Q libcupsfilters
    echo "Essa é a última versão funcional conhecida"
else
    echo "Essa versão libcupsfilters tem problemas para imprimir"
    pacman -Q libcupsfilters
    echo "Vamos fazer o downgrade dessa versão para a 2.1.1-4"
    echo "Essa é a última versão funcional conhecida"
    consertar_impressora
fi

# Substituir pacotes obsoletos
if [ -x "$(command -v neofetch)" ]; then
  echo "pacman -S fastfetch --noconfirm"
  pacman -S fastfetch --noconfirm
  echo "pacman -Rns neofetch --noconfirm"
  pacman -Rns neofetch --noconfirm
fi
