#!/bin/bash 
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = pacman" >> $HOME/0_data_atualizado.txt
echo "pacman -Syu --noconfirm"
pacman -Syu --noconfirm
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

echo "rm -rf /var/cache/pacman/pkg/*"
rm -rf /var/cache/pacman/pkg/*
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
echo "Obs: AUR desativado" >> $HOME/0_data_atualizado.txt

echo "Consertar aviso Aviso: btrfsmaintenance: local (1:0.5.2-1) é mais novo que extra (0.5.2-3) manjaro (02/10/2026)"
echo "pacman -Syuu --noconfirm btrfsmaintenance"
pacman -Syuu --noconfirm btrfsmaintenance # 02/10/2026

# Substituir pacotes obsoletos
if [ -x "$(command -v neofetch)" ]; then
  echo "pacman -S fastfetch --noconfirm"
  pacman -S fastfetch --noconfirm
  echo "pacman -Rns neofetch --noconfirm"
  pacman -Rns neofetch --noconfirm
fi
