#!/bin/bash 
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = pacman" >> $HOME/0_data_atualizado.txt
echo "pacman -Syu --noconfirm"
pacman -Syu --noconfirm
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

echo "rm -f /var/cache/pacman/pkg/*"
rm -f /var/cache/pacman/pkg/*
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
echo "Obs: AUR desativado" >> $HOME/0_data_atualizado.txt

# Substituir pacotes obsoletos
if [ -x "$(command -v neofetch)" ]; then
  echo "pacman -S fastfetch --noconfirm"
  pacman -S fastfetch --noconfirm
  echo "pacman -Rns neofetch --noconfirm"
  pacman -Rns neofetch --noconfirm
fi
