#!/bin/bash 
apt update
echo "apt update"
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = apt" >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

apt upgrade -y
echo "apt upgrade -y"
echo " " >> $HOME/0_data_atualizado.txt
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

apt clean
echo "apt clean -y"
apt autoremove -y
echo "apt autoremove -y"
apt autoclean -y
echo "apt autoclean -y"
apt autoremove --purge -y
echo "apt autoremove --purge -y"
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
