#!/bin/bash 
. detectar_distro
echo " " >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações do kernel Manjaro:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

if [ $KERNEL != "6.6." ] && [ $KERNEL != "6.12" ]; then
  echo "Instalando kernel 6.6"
  yes s | mhwd-kernel -i linux66
  echo "Esse é o kernel LTS de backup!"
fi

if [ $KERNEL != "6.12" ]; then
  echo "Instalando kernel 6.12"
  yes s | mhwd-kernel -i linux612
fi

if [ $KERNEL == "6.12" ]; then
  echo "Kernel 6.12 está instalado!"
  echo "Removendo kernel antigo se houver..."
  yes s | mhwd-kernel -r linux49
  yes s | mhwd-kernel -r linux414
  yes s | mhwd-kernel -r linux419
  yes s | mhwd-kernel -r linux54
  yes s | mhwd-kernel -r linux510
  yes s | mhwd-kernel -r linux515
  yes s | mhwd-kernel -r linux61
fi

echo "Final do script do kernel Manjaro:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
mhwd-kernel -li
