#!/bin/bash 
echo "flatpak update -y"
flatpak update -y
echo " " >> $HOME/0_data_atualizado.txt
echo "Flatpak atualizado em:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
