#!/bin/bash 
. detectar_distro
echo " " >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações do kernel Manjaro:" >> $HOME/0_data_atualizado.txt

if [ $KERNEL != "6.6." ] && [ $KERNEL != "6.12" ]; then
  echo "Instalando kernel 6.6"
  echo "Esse é o kernel LTS de backup!"
fi

if [ $KERNEL != "6.12" ]; then
  echo "Instalando kernel 6.12"
  echo "Esse é o kernel LTS mais novo!"
fi

echo "Final do script do kernel Manjaro:" >> $HOME/0_data_atualizado.txt
mhwd-kernel -li
