#!/bin/bash
. detectar_distro

echo "Iniciando atualização"
echo "O script de atualização da Hidraumak foi executado pela última vez em:" > $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

atualizar_scripts

if [ -x "$(command -v snap)" ]; then
  atualizar_snap
fi
if [ -x "$(command -v flatpak)" ]; then
  atualizar_flatpak
fi
if [ -x "$(command -v pacman)" ]; then
  atualizar_pacman
fi
if [ -x "$(command -v pamac)" ]; then
  atualizar_pamac
fi
if [ -x "$(command -v apt)" ]; then
  atualizar_apt
fi
if [ -x "$(command -v dnf)" ]; then
  atualizar_dnf
fi
if [ -x "$(command -v apk)" ]; then
  atualizar_apk
fi

cat $HOME/0_data_atualizado.txt
