#!/bin/bash 
echo "dnf check-update"
dnf check-update
echo " " >> $HOME/0_data_atualizado.txt
echo "Gerenciador de pacotes = dnf" >> $HOME/0_data_atualizado.txt
echo "Verificação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

echo "dnf upgrade"
dnf upgrade
echo " " >> $HOME/0_data_atualizado.txt
echo "Instalação das atualizações:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt

echo "dnf clean all"
dnf clean all
echo "dnf autoremove"
dnf autoremove
echo "dnf clean packages"
dnf clean packages
echo "dnf clean oldmaya"
dnf clean oldmaya
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza de pacotes:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
