#!/bin/bash
. detectar_distro
$INSTALAR manjaro-printer
$INSTALAR hplip-plugin
$INSTALAR avahi
$INSTALAR system-config-printer
sudo gpasswd -a $USER sys
sudo systemctl enable --now cups.service
sudo systemctl enable --now cups.socket
sudo systemctl enable --now cups.path
sudo systemctl enable --now avahi-daemon.service
system-config-printer