#!/bin/bash
. detectar_distro

sudo atualizar_scripts

# Scripts de downgrade
$INSTALAR downgrade

sudo DOWNGRADE_FROM_ALA=1 downgrade libcupsfilters
sudo systemctl restart cups
pacman -Q libcupsfilters
