#!/bin/bash

# Detectar a versão do kernel da distro
KERNEL=$(uname -r)
KERNEL=${KERNEL:0:4}

# Detectar o gerenciador de pacotes da distro
INSTALAR="echo"
PROCURAR="comando procurar não implementado:"
DISTRO="Desconhecido"
if ! [ -x "$(command -v apt-get)" ]; then
  :
else
  INSTALAR="sudo apt-get install -y"
  PROCURAR="apt-get search"
fi
if ! [ -x "$(command -v apt)" ]; then
  :
else
  INSTALAR="sudo apt install -y"
  echo 'O gerenciador de pacotes apt está instalado' >&2
  PROCURAR="apt search"
fi
if ! [ -x "$(command -v nala)" ]; then
  :
else
  INSTALAR="sudo nala install --assume-yes"
  echo 'O gerenciador de pacotes nala está instalado' >&2
fi
if ! [ -x "$(command -v pacman)" ]; then
  :
else
  echo 'O gerenciador de pacotes pacman está instalado' >&2
  INSTALAR="sudo pacman -S --noconfirm"
  PROCURAR="pacman -Ss"
fi
if ! [ -x "$(command -v pamac)" ]; then
  :
else
  echo 'O gerenciador de pacotes pamac está instalado' >&2
  INSTALAR="sudo pamac install --no-confirm"
  PROCURAR="pamac search"
fi
if ! [ -x "$(command -v dnf)" ]; then
  :
else
  echo 'O gerenciador de pacotes dnf está instalado' >&2
  INSTALAR="sudo dnf install -y"
fi
if ! [ -x "$(command -v yum)" ]; then
  :
else
  echo 'O gerenciador de pacotes yum está instalado' >&2
  INSTALAR="sudo yum install"
fi
if ! [ -x "$(command -v zypper)" ]; then
  :
else
  echo 'O gerenciador de pacotes zypper está instalado' >&2
  INSTALAR="sudo zypper install"
fi
if ! [ -x "$(command -v eopkg)" ]; then
  :
else
  echo 'O gerenciador de pacotes eopkg está instalado' >&2
  INSTALAR="sudo eopkg install"
fi
if ! [ -x "$(command -v apk)" ]; then
  :
else
  echo 'O gerenciador de pacotes apk está instalado' >&2
  INSTALAR="sudo apk add"
fi
if ! [ -x "$(command -v urpmi)" ]; then
  :
else
  echo 'O gerenciador de pacotes urpmi está instalado' >&2
  INSTALAR="urpmi"
fi
if ! [ -x "$(command -v xbps-install)" ]; then
  :
else
  echo 'O gerenciador de pacotes xbps-install está instalado' >&2
  INSTALAR="sudo xbps-install -S"
fi
if ! [ -x "$(command -v neko)" ]; then
  :
else
  echo 'O gerenciador de pacotes neko está instalado' >&2
  INSTALAR="sudo neko em"
fi
if ! [ -x "$(command -v pisi)" ]; then
  :
else
  echo 'O gerenciador de pacotes pisi está instalado' >&2
  INSTALAR="sudo pisi it"
fi
if ! [ -x "$(command -v guix)" ]; then
  :
else
  echo 'O gerenciador de pacotes guix está instalado' >&2
  INSTALAR="guix install"
fi

# Detectar distro
. /etc/os-release
echo " "
echo "Distribuição linux detectada:"
DISTRO=$ID
echo "$DISTRO"
echo "Kernel detectado:"
echo "$KERNEL"
uname -r
echo " "
