#!/bin/bash
instalar podman
instalar podman-docker
sudo systemctl enable --now podman
instalar distrobox
echo " "
echo "Para criar um container:"
echo "distrobox create --image ubuntu:18.04 --name ubuntu1804"
echo " "
echo "Para entrar em um container:"
echo "distrobox enter ubuntu1804"
