#!/bin/bash 
# exemplo de uso dos parâmetros de entrada 
echo "Tentando instalar: $1"

. detectar_distro

# Instalar pacote usando gerenciador de pacotes da distro
if ! [ -x "$(command -v $1)" ]; then
  echo "O pacote $1 não está instalado" >&2
  echo "Instalando $1 ..." >&2
  echo "$INSTALAR $1"
  $INSTALAR $1
else
  echo "O pacote $1 já estava instalado" >&2
fi
