#!/bin/bash 
# exemplo de uso dos parâmetros de entrada 
echo "Tentando instalar: $1"

# Detectar o gerenciador de pacotes da distro
INSTALAR="echo"
DISTRO="Desconhecido"
if ! [ -x "$(command -v apt-get)" ]; then
  :
else
  INSTALAR="sudo apt-get install -y"
  :
fi
if ! [ -x "$(command -v apt)" ]; then
  :
else
  INSTALAR="sudo apt install -y"
  :
fi
if ! [ -x "$(command -v nala)" ]; then
  :
else
  INSTALAR="sudo nala install --assume-yes"
  echo 'O gerenciador de pacotes nala está instalado' >&2
fi
if ! [ -x "$(command -v pacman)" ]; then
  :
else
  echo 'O gerenciador de pacotes pacman está instalado' >&2
  INSTALAR="sudo pacman -S --no-confirm"
fi
if ! [ -x "$(command -v pamac)" ]; then
  :
else
  echo 'O gerenciador de pacotes pamac está instalado' >&2
  INSTALAR="sudo pamac install --no-confirm"
fi
if ! [ -x "$(command -v dnf)" ]; then
  :
else
  echo 'O gerenciador de pacotes dnf está instalado' >&2
  INSTALAR="sudo dnf install -y"
fi
if ! [ -x "$(command -v yum)" ]; then
  :
else
  echo 'O gerenciador de pacotes yum está instalado' >&2
  INSTALAR="sudo yum install"
fi
if ! [ -x "$(command -v zypper)" ]; then
  :
else
  echo 'O gerenciador de pacotes zypper está instalado' >&2
  INSTALAR="sudo zypper install"
fi
if ! [ -x "$(command -v eopkg)" ]; then
  :
else
  echo 'O gerenciador de pacotes eopkg está instalado' >&2
  INSTALAR="sudo eopkg install"
fi
if ! [ -x "$(command -v apk)" ]; then
  :
else
  echo 'O gerenciador de pacotes apk está instalado' >&2
  INSTALAR="sudo apk add"
fi
if ! [ -x "$(command -v urpmi)" ]; then
  :
else
  echo 'O gerenciador de pacotes urpmi está instalado' >&2
  INSTALAR="urpmi"
fi
if ! [ -x "$(command -v xbps-install)" ]; then
  :
else
  echo 'O gerenciador de pacotes xbps-install está instalado' >&2
  INSTALAR="sudo xbps-install -S"
fi
if ! [ -x "$(command -v neko)" ]; then
  :
else
  echo 'O gerenciador de pacotes neko está instalado' >&2
  INSTALAR="sudo neko em"
fi
if ! [ -x "$(command -v pisi)" ]; then
  :
else
  echo 'O gerenciador de pacotes pisi está instalado' >&2
  INSTALAR="sudo pisi it"
fi
if ! [ -x "$(command -v guix)" ]; then
  :
else
  echo 'O gerenciador de pacotes guix está instalado' >&2
  INSTALAR="guix install"
fi

# Detectar distro
. /etc/os-release
echo " "
echo "Distribuição linux detectada:"
DISTRO=$ID
echo "$DISTRO"
echo " "

# Instalar pacote usando gerenciador de pacotes da distro
if ! [ -x "$(command -v $0)" ]; then
  echo "O pacote $1 não está instalado" >&2
  echo "Instalando $1 ..." >&2
  echo "$INSTALAR $1"
  $INSTALAR $0
else
  echo "O pacote $1 já estava instalado" >&2
fi
