#!/bin/bash
# Instalar Tailscale pelo script do site
curl -fsSL https://tailscale.com/install.sh | sh

# Fazer o login na conta Tailscale
sudo tailscale up --advertise-exit-node

# Configurar acesso a rede local
echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf                                                                                     ✔ 
echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
sudo tailscale set --advertise-routes=192.168.0.0/24,192.168.2.0/24
sudo tailscale set --exit-node-allow-lan-access
