#!/bin/bash

#Criar pasta para configuração
PASTA_AMBIENTE="$HOME/.venv/novnc"

# instalar dependencias
instalar openssl
instalar python
instalar python3
instalar tigervnc-common
instalar tigervnc
instalar git

#Configurar o python
if [ -x $(command -v python3) ]; then
  echo "Comando python3 encontrado!"
  instalar python3-venv
  instalar python3-pip
  PYTHON=python3
fi
if [ -x $(command -v python) ]; then
  echo "Comando python encontrado!"
  PYTHON=python
  instalar python-pip
fi

#Criar o ambiente virtual python
echo "Criando abiente virtual python em:"
echo "$PASTA_AMBIENTE"
$PYTHON -m venv $PASTA_AMBIENTE
source "$PASTA_AMBIENTE/bin/activate"
$PYTHON -m pip install websockify
$PYTHON -m pip install numpy
$PYTHON -m pip install novnc
mkdir - p "$PASTA_AMBIENTE/novnc-git"
cd "$PASTA_AMBIENTE/novnc-git"
git clone https://github.com/novnc/noVNC.git
#git clone -b v1.4.0 https://github.com/novnc/noVNC.git

#gerar certificados
openssl req -x509 -nodes -newkey rsa:3072 -keyout "$PASTA_AMBIENTE/novnc.pem" -out "$PASTA_AMBIENTE/novnc.pem" -days 3650

#gerar uma senha
vncpasswd
