#!/bin/bash

PASTA_AMBIENTE="$HOME/.venv/novnc"
PASTA_HTML_NOVNC="$PASTA_AMBIENTE/novnc-git/noVNC"
PASTA_CERTIFICADO="$PASTA_AMBIENTE/novnc.pem"
source "$PASTA_AMBIENTE/bin/activate"

#rodar vnc
x0vncserver -rfbauth ~/.vnc/passwd &

#Rodar usando novnc do ambiente virtual python
python -m websockify -D --web="$PASTA_HTML_NOVNC" --cert="PASTA_CERTIFICADO" 26901 localhost:5900

ip route | awk '{print $9}' | head -n 1 

#Rodar usando novnc snap
#websockify -D --web=/var/lib/snapd/snap/novnc/current --cert=$HOME/novnc.pem 26901 localhost:5900
#Rodar usando novnc do respositório do ubuntu
#websockify -D --web=/usr/share/novnc/ --cert=/home/ubuntu/novnc.pem 6080 localhost:5900
