#!/bin/bash

export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus

IP_DO_BACKUP="192.168.0.173"

ESTADO=$(ip neigh show "$IP_DO_BACKUP" | awk '{print $NF}')

case "$ESTADO" in
    REACHABLE|STALE|DELAY|PROBE)
        # Considera o equipamento acessível
        ;;
    *)
        zenity --error \
               --title="Backup offline!" \
               --width=300 \
               --text="PC do backup não acessível!"
        ;;
esac
